add_newline = true

[line_break]
disabled = true

[memory_usage]
disabled = false
threshold = 90

[git_status]
style = "yellow"
format = '([$conflicted$stashed$staged$deleted$renamed$modified$untracked$ahead_behind]($style) )'
conflicted = "ğŸ³"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = '!$count'
staged = '[+$count](green)'
renamed = "Â»$count"
deleted = "[âœ˜$count](bold red)"

#diverging
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_branch]
truncation_length = 20

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
python_binary = "python3"
format = '[(\($virtualenv\))]($style)'
